title: processing-python-text
hero_image: images/banner.png
description: processing-python-text description
version: 4
listed: false
copyedit: false
last_tested: "2021-09-27"
steps:
  - title: Create text
